import {NextResponse} from "next/server";
import JSZip from "jszip";

function id(){return crypto.randomUUID()}
export async function POST(req:Request){
 const {idea,version="1.21.31+"}=await req.json();
 if(!idea) return NextResponse.json({error:"Missing add-on idea."},{status:400});
 const bp=id(), rp=id(), module=id(), script=id();
 const safe=String(idea).slice(0,500);
 const files:any={};
 files["behavior_packs/AI_Addon_BP/manifest.json"]=JSON.stringify({format_version:2,header:{name:"AI Add-on Studio Behavior",description:safe,uuid:bp,version:[1,0,0],min_engine_version:[1,21,30]},modules:[{type:"data",uuid:module,version:[1,0,0]},{type:"script",language:"javascript",uuid:script,version:[1,0,0],entry:"scripts/main.js"}],dependencies:[{uuid:rp,version:[1,0,0]},{module_name:"@minecraft/server",version:"1.17.0"}]},null,2);
 files["behavior_packs/AI_Addon_BP/scripts/main.js"]=`import { world } from "@minecraft/server";\n\nworld.afterEvents.playerSpawn.subscribe((event)=>{\n  event.player.sendMessage("§a[AI Add-on Studio] Loaded successfully.");\n});\n`;
 files["behavior_packs/AI_Addon_BP/README.md"]=`# AI Add-on Studio Behavior Pack\n\nTarget: ${version}\n\nUser idea:\n${safe}\n\nThis is a safe starter generated by the factory. Add features incrementally and test each change.\n`;
 files["resource_packs/AI_Addon_RP/manifest.json"]=JSON.stringify({format_version:2,header:{name:"AI Add-on Studio Resources",description:"Generated resource pack",uuid:rp,version:[1,0,0],min_engine_version:[1,21,30]},modules:[{type:"resources",uuid:id(),version:[1,0,0]}],dependencies:[{uuid:bp,version:[1,0,0]}]},null,2);
 files["resource_packs/AI_Addon_RP/texts/en_US.lang"]="pack.name=AI Add-on Studio\n";
 files["resource_packs/AI_Addon_RP/README.md"]="# Resource Pack\n\nAsset placeholders and UI can be added here by the Asset AI.\n";
 files["QA_REPORT.md"]=`# QA REPORT\n\nTarget: ${version}\n\n- Unique UUIDs generated automatically\n- Behavior/resource dependency UUIDs matched\n- Script entry path exists\n- No infinite spawn loop included\n- Starter script uses a simple playerSpawn event\n- Back up worlds before testing\n\n## Requested idea\n${safe}\n\n## AI pipeline\nPlanner -> Bedrock Expert -> Asset AI -> QA AI\n`;
 files["README.md"]=`# AI Add-on Studio Generated Package\n\nIdea: ${safe}\nTarget: ${version}\n\nImport the behavior/resource packs into Minecraft Bedrock and enable them in a test world.\n\nThis package is a generated starter, not a guarantee that every requested feature is implemented.\n`;
 const zip=new JSZip(); for(const [p,c] of Object.entries(files)) zip.file(p,c);
 const blob=await zip.generateAsync({type:"base64"});
 return NextResponse.json({filename:"AI_Addon_Studio_Package.zip",download:"data:application/zip;base64,"+blob,preview:`BUILD COMPLETE\n\nTarget: ${version}\n\nAI idea:\n${safe}\n\nGenerated:\n✓ Behavior Pack manifest\n✓ Resource Pack manifest\n✓ Script API starter\n✓ Dependency wiring\n✓ QA report\n✓ README\n\nUUIDs were generated for this build.`});
}